import{a as g,S as h,i as y}from"./assets/vendor-BIn0hBn5.js";(function(){const n=document.createElement("link").relList;if(n&&n.supports&&n.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))i(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const a of r.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&i(a)}).observe(document,{childList:!0,subtree:!0});function o(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function i(t){if(t.ep)return;t.ep=!0;const r=o(t);fetch(t.href,r)}})();const P="51015530-5e955df2a81e83cea790abd16";g.defaults.baseURL="https://pixabay.com/api/";const m=async(e,n=1,o=15)=>{const i=new URLSearchParams({key:P,q:e,image_type:"photo",orientation:"horizontal",safesearch:"true",page:n,per_page:o});try{const t=await g.get("",{params:i}),{hits:r,totalHits:a}=t.data;return{hits:r,totalHits:a}}catch(t){throw t}},v=document.querySelector(".gallery");let D=new h(".gallery a");const w=e=>{const n=e.map(({webformatURL:o,largeImageURL:i,tags:t,likes:r,views:a,comments:q,downloads:$})=>`<div class='photo-card'>
          <a href="${i}">
            <img src="${o}" alt="${t}" loading="lazy" />
          </a>
          <div class="info">
            <div><p>Likes</p><p>${r}</p></div>
            <div><p>Views</p><p>${a}</p></div>
            <div><p>Comments</p><p>${q}</p></div>
            <div><p>Downloads</p><p>${$}</p></div>
          </div>
        </div>`).join("");v.insertAdjacentHTML("beforeend",n),D.refresh()},E=()=>{v.innerHTML=""},b=document.querySelector(".form"),M=document.querySelector(".loader"),L=document.querySelector(".load-more");let s=1,p="";const l=15;let c=new h(".gallery a",{captions:!0,captionsData:"alt",captionDelay:250});b.addEventListener("submit",O);L.addEventListener("click",R);async function O(e){e.preventDefault();const n=b.elements.search.value.trim();if(!n){x("Search query cannot be empty!");return}p=n,s=1,E(),u(!0),d(!1);try{const{data:o}=await m(p,s,l);if(o.hits.length===0){f("Sorry, there are no images matching your search query. Please try again!");return}w(o.hits),c?c.refresh():c=new h(".gallery a",{captions:!0,captionsData:"alt",captionDelay:250}),s*l>=o.totalHits?S("We're sorry, but you've reached the end of search results."):d(!0)}catch(o){f(`Something went wrong: ${o.message}`)}finally{u(!1)}}async function R(){s+=1,d(!1),u(!0);try{const{data:e}=await m(p,s,l);w(e.hits),c.refresh(),s*l>=e.totalHits?S("We're sorry, but you've reached the end of search results."):d(!0),H()}catch(e){f(`Something went wrong: ${e.message}`)}finally{u(!1)}}function x(e){y.warning({title:"Warning",message:e,position:"topRight"})}function f(e){y.error({title:"Error",message:e,position:"topRight"})}function S(e){y.info({title:"Info",message:e,position:"topRight"})}function H(){const e=document.querySelector(".photo-card");e&&window.scrollBy({top:e.getBoundingClientRect().height*2,behavior:"smooth"})}function u(e){M.style.display=e?"block":"none"}function d(e){L.style.display=e?"block":"none"}
//# sourceMappingURL=index.js.map
