import{a as p,S as $,i as h}from"./assets/vendor-BIn0hBn5.js";(function(){const n=document.createElement("link").relList;if(n&&n.supports&&n.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))i(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const a of o.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&i(a)}).observe(document,{childList:!0,subtree:!0});function r(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function i(t){if(t.ep)return;t.ep=!0;const o=r(t);fetch(t.href,o)}})();const M="51015530-5e955df2a81e83cea790abd16";p.defaults.baseURL="https://pixabay.com/api/";const f=async(e,n=1,r=15)=>{const i=new URLSearchParams({key:M,q:e,image_type:"photo",orientation:"horizontal",safesearch:"true",page:n,per_page:r});try{return(await p.get("",{params:i})).data}catch(t){throw t}},m=document.querySelector(".gallery");let l;const E=()=>{l?l.refresh():l=new $(".gallery a",{captions:!0,captionsData:"alt",captionDelay:250})},y=e=>{const n=e.map(({webformatURL:r,largeImageURL:i,tags:t,likes:o,views:a,comments:q,downloads:P})=>`<div class='photo-card'>
          <a href="${i}">
            <img src="${r}" alt="${t}" loading="lazy" />
          </a>
          <div class="info">
            <div><p>Likes</p><p>${o}</p></div>
            <div><p>Views</p><p>${a}</p></div>
            <div><p>Comments</p><p>${q}</p></div>
            <div><p>Downloads</p><p>${P}</p></div>
          </div>
        </div>`).join("");m.insertAdjacentHTML("beforeend",n),E()},O=()=>{m.innerHTML=""},g=()=>{var e;(e=document.querySelector(".loader"))==null||e.classList.remove("hidden")},v=()=>{var e;(e=document.querySelector(".loader"))==null||e.classList.add("hidden")},L=()=>{var e;(e=document.querySelector(".load-more"))==null||e.classList.remove("hidden")},w=()=>{var e;(e=document.querySelector(".load-more"))==null||e.classList.add("hidden")},S=document.querySelector(".form"),R=document.querySelector(".load-more");let s=1,d="";const c=15;S.addEventListener("submit",x);R.addEventListener("click",B);async function x(e){e.preventDefault();const n=S.elements.search.value.trim();if(!n){I("Search query cannot be empty!");return}d=n,s=1,O(),g(),w();try{const r=await f(d,s,c);if(r.hits.length===0){u("Sorry, there are no images matching your search query. Please try again!");return}y(r.hits),s*c<r.totalHits?L():b("We're sorry, but you've reached the end of search results.")}catch(r){u(`Something went wrong: ${r.message}`)}finally{v()}}async function B(){s+=1,w(),g();try{const e=await f(d,s,c);y(e.hits),s*c>=e.totalHits?b("We're sorry, but you've reached the end of search results."):L(),D()}catch(e){u(`Something went wrong: ${e.message}`)}finally{v()}}function I(e){h.warning({title:"Warning",message:e,position:"topRight"})}function u(e){h.error({title:"Error",message:e,position:"topRight"})}function b(e){h.info({title:"Info",message:e,position:"topRight"})}function D(){const e=document.querySelector(".photo-card");e&&window.scrollBy({top:e.getBoundingClientRect().height*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
